// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://robarhlwdrimpckcclng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvYmFyaGx3ZHJpbXBja2NjbG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTg5NDUsImV4cCI6MjA2NDYzNDk0NX0.yLocjXzZrlTdTK2n_91YJElM3HygtWNud2vezW6W_5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);